using JT_InfoApi.Domain;
using JT_InfoApi.Domain.Entities;
using System.Text.Json;
using System.Text;

namespace JT_InfoApi.API.Middlewares
{
    public class AuditMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly ILogger<AuditMiddleware> _logger;

        public AuditMiddleware(RequestDelegate next, ILogger<AuditMiddleware> logger)
        {
            _next = next;
            _logger = logger;
        }

        public async Task InvokeAsync(HttpContext context, AppDbContext db)
        {
            context.Request.EnableBuffering();

            string requestBodyText = "";
            using (var reader = new StreamReader(context.Request.Body, Encoding.UTF8, true, 1024, true))
            {
                requestBodyText = await reader.ReadToEndAsync();
            }
            context.Request.Body.Position = 0;

            int? custCode = await GetCustomerIdAsync(context);

            var endpoint = context.GetEndpoint();

            var controllerName = endpoint?.Metadata?
                .GetMetadata<Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor>()
                ?.ControllerName;

            var methodName = endpoint?.Metadata?
                .GetMetadata<Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor>()
                ?.ActionName;

            // 1️⃣ Capture QueryString
            var queryString = context.Request.QueryString.Value;
            var requestBody = context.Request.Body?.ToString();

            // 2️⃣ Capture Response Body
            var originalBodyStream = context.Response.Body;
            using var responseBodyStream = new MemoryStream();
            context.Response.Body = responseBodyStream;

            try
            {
                // Continue pipeline
                await _next(context);

                // Read response generated by controller
                context.Response.Body.Seek(0, SeekOrigin.Begin);
                string responseBodyText = await new StreamReader(context.Response.Body).ReadToEndAsync();
                context.Response.Body.Seek(0, SeekOrigin.Begin);

                // 3️⃣ Insert audit log
                var log = new Audit
                {
                    CustCode = custCode,
                    MethodName = methodName,
                    ControllerName = controllerName,
                    HttpMethod = context.Request.Method,
                    StatusCode = context.Response.StatusCode,
                    Timestamp = DateTime.Now,
                    QueryString = queryString,
                    RequestBody = requestBodyText,
                    ResponseBody = responseBodyText
                };

                db.Audits.Add(log);
                await db.SaveChangesAsync();

                // Write response back to client
                await responseBodyStream.CopyToAsync(originalBodyStream);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                context.Response.Body = originalBodyStream;
                throw;
            }
        }


        private async Task<int?> GetCustomerIdAsync(HttpContext context)
        {
            // 1️⃣ Try from Header
            if (context.Request.Headers.TryGetValue("custCode", out var headerValue))
            {
                if (int.TryParse(headerValue, out var id)) return id;
            }

            // 2️⃣ Try from QueryString
            if (context.Request.Query.TryGetValue("custCode", out var queryValue))
            {
                if (int.TryParse(queryValue, out var id)) return id;
            }

            // 3️⃣ Try from Body
            context.Request.EnableBuffering();
            using var reader = new StreamReader(context.Request.Body, Encoding.UTF8, true, 1024, true);
            string bodyText = await reader.ReadToEndAsync();
            context.Request.Body.Position = 0;

            if (!string.IsNullOrEmpty(bodyText))
            {
                try
                {
                    var json = JsonDocument.Parse(bodyText);
                    if (json.RootElement.TryGetProperty("custCode", out var prop))
                    {
                        if (prop.TryGetInt32(out var id))
                            return id;
                    }
                }
                catch( Exception ex)
                {
                    _logger.LogError(ex.Message);
                }
            }

            return null;
        }

    }

}
