using JT_InfoApi.Domain;
using JT_InfoApi.Domain.Entities;

namespace JT_InfoApi.API.Middlewares
{
    public class AuditMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly ILogger<AuditMiddleware> _logger;

        public AuditMiddleware(RequestDelegate next, ILogger<AuditMiddleware> logger)
        {
            _next = next;
            _logger = logger;
        }

        public async Task InvokeAsync(HttpContext context, AppDbContext db)
        {
            int? custCode = GetCustomerIdFromRequest(context);

            var endpoint = context.GetEndpoint();

            var controllerName = endpoint?.Metadata?
                .GetMetadata<Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor>()
                ?.ControllerName;

            var methodName = endpoint?.Metadata?
                .GetMetadata<Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor>()
                ?.ActionName;

            // 1️⃣ Capture QueryString
            var queryString = context.Request.QueryString.Value;

            // 2️⃣ Capture Response Body
            var originalBodyStream = context.Response.Body;
            using var responseBodyStream = new MemoryStream();
            context.Response.Body = responseBodyStream;

            try
            {
                // Continue pipeline
                await _next(context);

                // Read response generated by controller
                context.Response.Body.Seek(0, SeekOrigin.Begin);
                string responseBodyText = await new StreamReader(context.Response.Body).ReadToEndAsync();
                context.Response.Body.Seek(0, SeekOrigin.Begin);

                // 3️⃣ Insert audit log
                var log = new Audit
                {
                    CustCode = custCode,
                    MethodName = methodName,
                    ControllerName = controllerName,
                    HttpMethod = context.Request.Method,
                    StatusCode = context.Response.StatusCode,
                    Timestamp = DateTime.Now,
                    QueryString = queryString,
                    ResponseBody = responseBodyText
                };

                db.Audits.Add(log);
                await db.SaveChangesAsync();

                // Write response back to client
                await responseBodyStream.CopyToAsync(originalBodyStream);
            }
            catch
            {
                context.Response.Body = originalBodyStream;
                throw;
            }
        }


        private int? GetCustomerIdFromRequest(HttpContext context)
        {

            if (context.Request.Headers.TryGetValue("X-Cust-Code", out var headerValue))
            {
                if (int.TryParse(headerValue, out var id))
                    return id;
            }

            if (context.Request.Query.TryGetValue("custCode", out var queryValue))
            {
                if (int.TryParse(queryValue, out var id))
                    return id;
            }

            return null;
        }
    }

}
