// <auto-generated />
using System;
using JT_InfoApi.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JT_InfoApi.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111101555_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.JT_Public_Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PHolDate")
                        .HasColumnType("date");

                    b.Property<string>("PHolDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RegionCode");

                    b.ToTable("JT_Public_Holidays", (string)null);
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.Region", b =>
                {
                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CtyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtyDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionCode");

                    b.HasIndex("CountryCode");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.JT_Public_Holiday", b =>
                {
                    b.HasOne("JT_InfoApi.Domain.Entities.Region", "Region")
                        .WithMany("PublicHolidays")
                        .HasForeignKey("RegionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.Region", b =>
                {
                    b.HasOne("JT_InfoApi.Domain.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("JT_InfoApi.Domain.Entities.Region", b =>
                {
                    b.Navigation("PublicHolidays");
                });
#pragma warning restore 612, 618
        }
    }
}
